### ISSUE TITLE
Czy chcemy wymagać przestrzegania PSR?

### ISSUE THREAD

**Issue by event15** [CodersCommunity/forum.pasja-informatyki.local#108]
Wystarczy add reaction 👍 lub 👎

**Comment by event15** [comment]
Zostawie to issue do końca miesiąca. Każdy będzie mógł zagłosować. Oczywiście - nie mówię o jakimś super restrykcyjnym trzymaniu się tego PSR, ale warto chociaż troszkę trzymać się jakiegoś standardu pisania, żeby wszystko co tworzymy od siebie, wyglądało w miarę porządnie.

**Comment by awaluk** [comment]
Spoko, ja jestem za PSR-2. Głos oddałem.

**Comment by qwercik** [comment]
Teraz przynajmniej będą jawnie określone zasady, więc jestem za.
Ale q2a nie ma jakiego swojego style guide? Jeśi ma to nie lepiej byłoby się go trzymać, niż wtrącać do projektu kolejny i robić bałagan?

**Comment by event15** [comment]
@qwercik https://github.com/q2a/question2answer/blob/master/CONTRIBUTING.md. Nie koliduje to z żadnym z PSR :)

**Comment by Patrycjerz** [comment]
Dobrze, jak tak chce większość, to niech tak będzie. Przynajmniej będzie wiadomo, w jaki sposób mamy pisać. Boję się jedynie o to, że taki zapis może wystraszyć niektórych przy wprowadzaniu własnych zmian, bo np. zaczynają z PHP lub nie znają PSR-2 i innych zasad czystego kodu, ale rozumiem, że nawet najgorszy kod zostanie tutaj zrecenzowany i poprawiony.

Mam jedno pytanie. Jak wyglądać będzie sprawa stylistyki kodu? Czy tabulacje mają być zamienione na cztery spacje a klamra początkowa ma być w tej samej linii co komenda? A może chodzi jedynie o samą logikę kodu, a styl jest sprawą drugorzędną?

**Comment by awaluk** [comment]
Bądźmy szczerzy: tych początkujących którzy wprowadzaliby zmiany po prostu nie ma, mało kto pracuje przy tym kodzie (niestety, ale z drugiej strony nie dziwię się). Nie można oczywiście wykluczyć że taka osoba się pojawi, chociażby jedna. Ale jak będzie z tym problem to dostanie info że trzeba poprawić zgodnie z PSR-2 i nauczy się przy okazji czegoś, co jest praktycznie standardem w PHP.

Co do PSR-2 proponuję po prostu przeczytać to: http://www.php-fig.org/psr/psr-2/ i będziesz wszystko wiedział.

**Comment by Patrycjerz** [comment]
Ja wiem, że w tych przypadkach jest "MUST", no ale przeczytałem od @event15 
> Oczywiście - nie mówię o jakimś super restrykcyjnym trzymaniu się tego PSR [...]
i się zastanawiam, jak to będzie respektowane.

**Comment by event15** [comment]
Z mojej strony będę zaznaczał, że powinniśmy się stosować do standardów programowania w PHP a nie w innych językach, które są opisane w PSR. Jednak nie będzie to koniecznym warunkiem, który będzie decydował o przyjęciu lub odrzuceniu MR. W miarę czasu i możliwości najpewniej będę osobiście zmieniał formatowanie na zgodne z psr, jeśli ktoś okaże się uparty w swoich nawykach. 
Jednocześnie zakładam, że nikt specjalnie na złość nie będzie olewał tego, że będziemy zalecać pisanie zgodnie z tym PSR :)

**Comment by event15** [comment]
Już jeste 6 osób na 10 z łapką w górę. Demokratycznie można byłoby już zamknąć ten issue :) 
Pozostałoby edytowanie readme i hajda :)

**Comment by qwercik** [comment]
Myślę, że stan głosowania się drastycznie nie zmieni, więc chyba nawet można zamknąć :)
