### ISSUE TITLE
Podbijanie pytania przez komentarze

### ISSUE THREAD

**Issue by trib0r3** [CodersCommunity/forum.pasja-informatyki.local#109]
Pomysł zasugerowany przez: PaulGilbert na [forum](https://forum.pasja-informatyki.pl/308915/wprowadzenie-podbijania-watkow-po-komentarzu).

## Idea

Napisanie komentarza pod pytaniem / odpowiedzią do pytania "odświeża" pytania na liście pytań podbijając jego pozycję (tak jak to jest w przypadku odpowiedzi na pytania).

## Powód

Wątek pozornie umiera (gdyż dyskusja toczy się w komentarzach), dyskusja toczy się tylko pomiędzy wcześniejszymi uczestnikami rozmowy.

Notka ode mnie: także daje + do tego pomysłu, czasem brakuje powiewu świeżych głosów w dyskusji, ale że wątek "upada", to marne są na to szanse :(

**Comment by awaluk** [comment]
Moja opinia jest w odpowiedzi na forum.

Obawiam się, że taka zmiana nie będzie najlepszym pomysłem. Z jednej strony tak, na plus, ale z drugiej będzie ciągle wybijało toczące się gdzieś małe dyskusje, a nowe pytania będą spadały ze strony głównej. Dlatego nie jestem przekonany co do tego rozwiązania, co nie znaczy że je odrzucam.

Można rozważyć to co napisał w temacie Benek, czyli możliwość przełączenia sobie tego indywidualnie. Poza tym myślę, że warta wprowadzenia jest opcja odświeżania pytania przyciskiem oraz możliwość włączenia/wyłączenia obserwowania danego postu.

**Comment by Patrycjerz** [comment]
Wg mnie również to rozwiązanie nie ma większego sensu. Takie ciągłe wykopki są mocno dezorientujące. Najlepiej stworzyć przycisk (np. jednorazowy dla danego pytania) przenoszący je na górę. Później odświeżanie jest zablokowane w celach bezpieczeństwa. Administracja ma jednak nieograniczoną możliwość jego używania. Może jak kiedyś znajdę czas, chęci i możliwości, to spróbuję coś takiego zaprojektować, ale niczego nie obiecuję.

**Comment by qwercik** [comment]
To o czym mówi @Patrycjerz wydaje mi się najrozsądniejszym rozwiązaniem. Tylko co wtedy z "odpowiedziami" tworzonymi przez autorów pytania w celu odświeżenia pytania? Mamy je ukrywać?
No i boję się trochę wprowadzenia tego, żeby nie było tak, że nagle nawet najstarsze pytania będą mogły zostać odkopane. Więc moja propozycja jest taka - lex retro non agit (prawo nie działa wstecz), czyli wszystkie poprzednie pytania będą miały zablokowaną możliwość odświeżenia, a owy "odświeżacz" będą mogli zastosować tylko autorzy tych nowszych pytań. Co myślicie?

**Comment by awaluk** [comment]
@qwercik gdybyśmy mieli taką funkcję to tak, odpowiedzi pisane w celu odświeżenia ukrywać, ewentualnie informować tworzących o takowej funkcji gdyby nie wiedzieli. Ale jeśli ktoś już raz by odświeżył pytanie przy użyciu przycisku i dalej pisał głupie odpowiedzi aby tylko podbić pytanie to tak, ukrywać i zwracać uwagę że tak nie wolno, a gdyby ktoś bardzo to łamał to banować. A blokada tego dla wcześniejszych pytań... Moim zdaniem to nie będzie tak duży problem, wątpliwe że nagle ludzie przyjdą i zaczną odgrzebywać stare pytania. Najpierw to trzeba taką funkcję w ogóle wprowadzić (co w Q2A może być trudne), później martwić się takimi rzeczami.

**Comment by event15** [comment]
A czy przypadkiem odpowiedź typu "najlepsza" nie podbija całego komentarza na samą górę?

**Comment by awaluk** [comment]
@event15 zaznaczenie odpowiedzi jako najlepsza przenosi ją na górę danego pytania, widać to też na stronie "Ostatnia aktywność".
