### ISSUE TITLE
Brak menu kontekstowego CKEditor na serwerze, lokalnie wszystko działa

### ISSUE THREAD

**Issue by Patrycjerz** [CodersCommunity/forum.pasja-informatyki.local#117]
Ciekawi mnie powód tego. Na forum uruchomionym z maszyny Vagrant klikając prawym przyciskiem myszy w obszarze edytora wyświetla nam się menu kontekstowe z różnymi opcjami (wklej, edytuj kod źródłowy itp.). Na forum zaś tej opcji nie ma. Niby kod ten sam, a jednak działanie inne. A oto wizualizacja problemu.

Lokalnie:
![image](https://user-images.githubusercontent.com/15708308/36165695-b479f8c0-10f0-11e8-949c-0374495de148.png)

Na forum:
![image](https://user-images.githubusercontent.com/15708308/36165792-faed04e6-10f0-11e8-8cc9-b9924013dc85.png)

**Comment by Patrycjerz** [comment]
Tak w ogóle lokalnie też brakuje pewnych elementów, np. tego czerwonego paska ze znakiem entera.

![image](https://user-images.githubusercontent.com/15708308/36166345-71e9f972-10f2-11e8-9aab-155f76453753.png)

**Comment by awaluk** [comment]
Jeśli się nie mylę to Ustawienia > Wtyczki > CKEditor
W _Other configuration_ mamy na forum:
`removePlugins:'elementspath,contextmenu,tabletools,liststyle',`
a lokalnie jest tylko `removePlugins:'elementspath',` - prawdopodobnie to odpowiada za menu po kliknięciu prawym przyciskiem myszy.

A ta czerwona linia pojawia się np. gdy wstawimy cytat (aby łatwo go opuścić) i u mnie pojawia się zarówno na forum jak i lokalnie.

**Comment by Patrycjerz** [comment]
Racja, mi też działa ten pasek. Po prostu miałem jakąś niefortunną treść pytania i za żadne skarby nie chciał mi się pojawić.
