### ISSUE TITLE
Labele - po polsku czy angielsku?

### ISSUE THREAD

**Issue by Mariusz08** [CodersCommunity/forum.pasja-informatyki.local#132]
Obecnie labele są po angielsku - jesteśmy polską społecznością, więc pomyślałem, że można to spolszczyć. Taka mała ankieta. Wystarczy add reaction :+1:(za spolszczeniem)  albo :-1:  (niech zostanie tak jak jest)

**Comment by awaluk** [comment]
Moim skromnym zdaniem bez znaczenia - sam GitHub też nie jest przetłumaczony. Część rzeczy które my piszemy jest po polskie, część po angielsku (commity), więc i tak będzie to gdzieś tam pomieszane. Do tego jeszcze to tylko GitHub, mało kto tu zagląda (niestety) i raczej nie jest to nikt przypadkowy, a osoba która mniej więcej ogarnia o co chodzi.

**Comment by Mariusz08** [comment]
>  bez znaczenia

Mało osób tutaj zagląda, przewaga głosów też nie jest duża a więc zostaje jak jest.
