### ISSUE TITLE
Link do udostępnienia taki jak na stackoverflow

### ISSUE THREAD

**Issue by Mariusz08** [CodersCommunity/forum.pasja-informatyki.local#136]
Moje pytanie dotyczy #89 - tam kod wymaga poprawy, ale czy działanie jest OK? Mógłbym poprawić ten kod, ale z tego co widzę to po kliknięciu udostępnij wyskakuje link taki sam jak z URL + id pytania. Tak jest ok, czy może by go skrócić np. do takiej formy
https://forum.pasja-informatyki.pl/a/12345
?

**Comment by awaluk** [comment]
W zasadzie linki mogą być skracane, nie widzę problemu. Moim zdaniem dobrze by też było, aby po wejściu na skrócony link następowało przekierowanie, aby i tak trafiało się na ten właściwy. Poza tym działanie tam było chyba ok, tylko trzeba jakoś to poprawić też w sensie wizualnym, ładnie przygotować itd.
