### ISSUE TITLE
Powody zgłoszenia (PR: #143)

### ISSUE THREAD

**Issue by Mariusz08** [CodersCommunity/forum.pasja-informatyki.local#138]
Wiele razy padały pomysły nt. stworzenia powodu dla zgłoszenia. Ja taki wykonuje, już kończę, tylko potrzebuje konkretną listę powodów dla zgłoszenia. Plugin, który przerabiam pod potrzeby forum, obsługuje 10 powodów, więc fajnie byłoby się w tej dziesiątce zmieścić. Moja propozycja:
Kod nie wstawiony w bloczek
Spam
Duplikat
Ogromna ilość błędów ortograficznych
Złe formatowanie

**Comment by qwercik** [comment]
A moim zdaniem lepiej byłoby może nie określać z góry powodów, ale pozwolić się wykazać zgłaszającemu - problemy zawsze mogą być różne, nie wszystko podciągniesz pod konkretną opcję.
Ale skoro chcesz, to podpowiadam:
- Obraza
- Promowanie treści nielegalnych
- Nieoznakowany link partnerski (:smiley:)
- Niepoprawna kategoria
- Złe otagowanie

**Comment by awaluk** [comment]
Moja propozycja to był mechanizm w którym byłyby jakieś przyciski z
powodami i po kliknięciu w konkretny w pole tekstowe dodaje się tenże
powód. Dzięki temu można byłoby dodać wiele do jednego oraz dowolnie
formatować ich treść/edytować, a jednocześnie ten kto chce tylko szybko
wybrać konkretny powód zrobi to nadal jednym kliknięciem.

To oczywiście nie znaczy że tak musi być. Listę powodów i tak trzeba
zebrać. Z ilością bym nie przesadzał nawet nie tylko ze względu na
ograniczenia programowe (bo te zapewne da się obejść), lecz po prostu
wygody - użytkownik wchodzi i klika szybko co trzeba, a nie czyta
litanię powodów i się głowi co wybrać.

**Comment by Mariusz08** [comment]
Oczywiście, w okienku jest możliwość wpisania własnego powodu, a nawet więcej: po wybraniu któregoś powodu z listy jest on wpisywany do pola tekstowego.

**Comment by event15** [comment]
Moim zdaniem powody powinny być dostępne domyślnie, a jeśli ktoś nie znajdzie to musi kliknąć "Inny" w którym wpisze własnoręcznie, jaki jest powód.

**Comment by event15** [comment]
A masz już jakiś screenshot?

**Comment by event15** [comment]
Czemu zamknąłeś?
