### ISSUE TITLE
Sidebar widoczny w małych rozdzielczościach na przegądarkach pecetowych

### ISSUE THREAD

**Issue by xandros15** [CodersCommunity/forum.pasja-informatyki.local#14]
Dla wszystkich szerokości poniżej 1180px: https://i.imgur.com/DO0gDsq.png

Jak poprawić: np. dodać do selektora ``.qa-sidepanel`` ``display:none`` przy ``@media screen and (max-width: 1179px)``

**Comment by event15** [comment]
Fixed https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/16
