### ISSUE TITLE
503 - WebSocket

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/forum.pasja-informatyki.local#148]
Websocket w konsoli rzuca następującym błędem:

**async-questions-list.js:9** WebSocket connection to 'wss://forum.pasja-informatyki.pl:3000/' failed: Error during WebSocket handshake: Unexpected response code: 503

Wystarczy wejść na https://forum.pasja-informatyki.pl/

**Comment by awaluk** [comment]
Wynika to z tego, że socket (ten w node) nie jest uruchomiony. A ten nie jest uruchomiony bo zaraz po uruchomieniu pada z jeszcze nieznanej przyczyny:

> > http-websocket-server@1.0.0 serve
> > node dist/index.js
> 
> events.js:160
>      throw er; // Unhandled 'error' event
>      ^
>
>Error: write EPIPE
>    at exports._errnoException (util.js:1008:11)
>    at WriteWrap.afterWrite (net.js:793:14)

**Comment by efiku** [comment]
https://github.com/websockets/ws/issues/1123

**Comment by awaluk** [comment]
Websocket został przebudowany i rozbudowany - obecnie samego opisanego tu problemu nie zaobserwowano. W planach jest dalsza rozbudowa i przywrócenie funkcjonalności z nim związanych.
