### ISSUE TITLE
Wykrywanie SPOJów

### ISSUE THREAD

**Issue by ChrissP92** [CodersCommunity/forum.pasja-informatyki.local#15]
Napisałem skrypt, który wykrywa, gdy użytkownik zakładając temat wpisze w jego tytule słowo "spoj" oraz, jeśli w treści pytania wystąpi fraza "pl.spoj.com".
Kod jest w wersji alfa. Wiem, że troszkę śmietnik i trzeba go poprawić.
Natomiast ciekaw jestem jakie macie propozycje dotyczące samego działania wykrywacza SPOJa - jak to ma się zachowywać. Jakieś sugestie, coś poprawić?
https://github.com/CodersCommunity/forum.pasja-informatyki.local/commit/088891d54409b071e16ec3274d74eaad03ca6613

_To mój pierwszy issue, więc mogłem coś lub gdzieś źle napisać._

**Comment by qwercik** [comment]
Może się przydać :)

**Comment by awaluk** [comment]
Pomysł jak najbardziej popieram - z pewnością znajdą się osoby które nie zwrócą na to szczególnie uwagi, ale jest szansa, że ktoś się zainteresuje.

Samo działanie w tytule jest okej, właśnie przetestowałem. Nie wiem tylko co się dzieje, ze w treści pytania nie działa mi wykrywanie. Konsola rzuca jeden błąd, chyba z tym związany:
> qa-ask.js?1.7.3:349 Uncaught TypeError: Cannot read property 'addEventListener' of null

Poza tym dałbym komunikat większy i w innym miejscu - w tytule pytania zasłania spory kawałek inputa, osobiście bardziej by mi się podobało gdyby było pod czy nad inputem, aby użytkownik widział co pisze.

**Comment by ChrissP92** [comment]
@awaluk , ten błąd który Ci rzucił jest związany z `ckeditor.addEventListener('input', function()`. Miałem z tym trochę problemów, gdyż (jak z resztą w którymś komentarzu zapisałem) CKEditor kończy się ładować jeszcze później niż zdarzenie `load` ma miejsce (a ono powinno czekać, aż wszystkie skrypty, CSSy i cały DOM się załaduje). Dlatego też dałem tam Mutation Observer - on obserwuje, że w rodzicu CKEditora zmieniła się zawartość (czyli dodał się `<iframe>` z edytorem. Sprawdziłem u siebie i też ten błąd wystąpił, ale po odświeżeniu strony już działało (aczkolwiek nieco dłużej się strona ładowała).
Postaram się to poprawić.

@event15 , zaproponował aby dodać linka (na forum) do zasad umieszczania zadań ze SPOJ,

**Comment by awaluk** [comment]
@ChrissP92 próbowałem kilka razy odświeżać i u mnie niestety problem występuje ciągle - nie udało mi się ani razu przetestować działania tego w treści pytania.

A linka można dodać, na formularzu zadawania pytania mamy coś takiego z linkiem, który też prowadzi do tego tematu:
> W pytaniach dotyczących serwisu SPOJ nie wstawiaj całego kodu z zadania - [nie psuj zabawy innym](http://forum.pasja-informatyki.pl/90416/spoj-zasady-umieszczania-postow).

**Comment by ChrissP92** [comment]
Hmm, a odświeżałeś też z CTRL + F5? Jeśli będą z tym problemy, to poszukam innego rozwiązania niż Mutation Observer. Ewidentnie `<iframe>` z CKEditorem ładuje się z opóźnieniem, a JS chce się do niego dostać, zanim on jest gotowy.

**Comment by Comandeer** [comment]
Uhm, użycie `MutationObserver` do wykrycia kiedy CKEditor się wczyta? Widziałem różne rzeczy, ale tym mnie serio zaskoczyłeś ;)

CKEditor udostępnia sporo zdarzeń, dzięki którym można się spokojnie podpiąć pod edytorek wtedy, gdy potrzeba. Tutaj można spróbować użyć choćby [zdarzenia `loaded`](http://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-loaded).

> CKEditor kończy się ładować jeszcze później niż zdarzenie load ma miejsce (a ono powinno czekać, aż wszystkie skrypty, CSSy i cały DOM się załaduje)

Nie. Skrypty asynchroniczne czy ciągnięte Ajaksem są poza kontrolą tego zdarzenia.

**Comment by ChrissP92** [comment]
Dzięki @Comandeer za cenną wskazówkę. Trochę mi zeszło nad próbowaniem w jaki sposób skrypt ma poczekać aż CKEditor się załaduje. Myślałem o `setTimeout`, ale czasem strona może dłużej się ładować i wtedy to nie miało by sensu. Początkowo nie chciałem pakować się w API(?) CKEditora, aby skrypt był jak najprostszy. Jednak, jeśli radzisz skorzystać z eventów CKEditora, to grzechem będzie z tego nie skorzystać :)

**Comment by ChrissP92** [comment]
Poprawiona wersja: https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/20
