### ISSUE TITLE
Https na .local

### ISSUE THREAD

**Issue by event15** [CodersCommunity/forum.pasja-informatyki.local#153]
W związki ze zmianami na forum, chciałbym przedyskutować możliwość dodania jakiegoś let's encrypta do lokalnej wersji forum. 
Zmiany proponowane przeze mnie powodują, że nie da się sprawdzić tego lokalnie. 
Inną sprawą jest to, że przez brak https lokalnie mamy rozjazd z produkcją, na której jest wymuszony.
@efiku gdybyś znalazł chwilę to spróbowalibyśmy coś ogarnąć, bo nie mam na tyle ogarnięcia w ansible, żeby czegoś nie spieprzyć. 
@awaluk prosiłbym również Ciebie o współpracę.

**Comment by efiku** [comment]
Ja to bym wszystko przeniósł na dockera, w podobnej formie co mam tu: https://github.com/efiku/panel-szkolny za pomocą docker-compose fajnie się to spina. 
Co do certyfikatu.. tu chyba jak chcesz na lokalnych to trzeba będzie raczej self-signed choć aż tak bardzo się na tym nie znam.

**Comment by awaluk** [comment]
Forum przeniesione na Dockera. Można dodać SSL, byłby self signed, ale zastanowiłbym się czy jest to dla nas na tyle istotna rzecz, aby to robić.

**Comment by event15** [comment]
Nie jest to potrzebne. Na potrzeby testowania CSP można, to zrobić, ale bez upychania tego w kod forum na gh.
