### ISSUE TITLE
Zwijalne bloczki z kodem

### ISSUE THREAD

**Issue by ChrissP92** [CodersCommunity/forum.pasja-informatyki.local#19]
Napisałem skrypt, który automatycznie zwija bloczki z kodem dłuższe niż X linijek (ustawiłem na 30, ale można zmienić za pomocą zmiennej `numberOfLines`). Można taki bloczek rozwijać/zwijać przyciskiem + obok przycisku znajduje się opis języka, w jakim został napisany kod wewnątrz bloczka.

Kod: https://github.com/CodersCommunity/forum.pasja-informatyki.local/tree/collapsing-blocks-of-code

**[UPDATE]**
Znacząco uproszczony kod: https://github.com/CodersCommunity/forum.pasja-informatyki.local/commit/e1b8f8355da795615c8460ce16f168853a951d1b

**Comment by efiku** [comment]
PROSZĘ robic ref do PR odnośnie TEJ issue, bo później to wisi i nie wiadomo do czego.
