### ISSUE TITLE
Zmiana nicku przez użytkowników

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#192]
Obecnie nazwy użytkownika zmieniam tylko ja na prośby. Jest to spowodowane tym, że kiedyś, gdy można to było robić samemu bez ograniczeń, pojawiły się przypadki głupich zabaw zmian co chwilę i był z tym problem.

Nie jest to jednak zbyt wygodne, szczególnie dla użytkownika. Warto byłoby wprowadzić możliwość zmiany przez użytkowników (odpowiednie pole jest w edycji konta), ale musiałaby ona być jakoś ograniczona. Najlepszym rozwiązaniem jest chyba czas - czyli np. umożliwienie zmiany raz na 14 dni, 30, czy jeszcze inną liczbę.

**Comment by event15** [comment]
W moim odczuciu powinien być to formularz z oczekiwaniem na akceptacje moderacji/administracji. Wtedy zaistniałaby możliwość kontrolowania tych zmian nicków. 
Na koncie powinny być też zapisane poprzednie nazwy użytkowników widoczne dla moderacji/administracji.

**Comment by awaluk** [comment]
Też jest to akceptowalna opcja. Wydaje się jednak, że jest bardziej rozbudowana i trochę niepotrzebna. Teraz osoby zgłaszają się do mnie i tak naprawdę nie było sytuacji, abym odmówił tej zmiany, a już na pewno nie ze względu na zły nick. Były tylko sytuacje, gdy ktoś prosił o zmianę na już zajęty. Poza tym tworząc nowe konta nazwy użytkownika też nie są akceptowane. Po co mielibyśmy więc ręcznie akceptować zmianę? Jeśli tylko po to, aby wejść na użytkownika i zobaczyć kiedy ostatnio zmieniał i czy nie robi tego za często, to można ustawić zaproponowany przeze mnie limit czasowy i efekt będzie taki sam.

Historia poprzednich nazw jak najbardziej, obowiązkowo wręcz.

**Comment by awaluk** [comment]
Zrobione w #244
