### ISSUE TITLE
Zmiana domyślnie wybranej podkategorii na brak wyboru

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#213]
Zadając pytanie dokonuje się wyboru kategorii. Domyślnie główna kategoria nie jest wybrana i to jest ok. Po wyborze "Programowanie" pojawia się jednak wybór podkategorii, gdzie domyślnie błędnie zaznaczona jest "C i C++". Powoduje to problem tego typu, że często wiele pytań ma dobrą kategorię główną i złą podkategorię, prawdopodobnie ludzie po prostu nie zwracają uwagi na to, że trzeba coś tam jeszcze wybrać. Należy zmienić więc to tak, aby podkategoria nie była domyślnie wybierana - podobnie jak kategoria, musi być domyślnie pusta. Gdy ktoś nie zauważy pola, to na walidacji przy próbie dodania pytania powinien dostać błąd i mamy większą szansę że wybierze właściwie.

**Comment by JSHoliq** [comment]
Pusta podkategoria jest dodawana dynamicznie na froncie na podstawie zmiennych `qa_cat_allownosub` oraz `qa_cat_allownone` przekazywanych do frontu z backendu, a ustawianych w bazie w tabeli `qa_options` w polach `allow_no_sub_category` oraz `allow_no_category`.
Flaga `qa_cat_allownosub` jest 0, dlatego w podkategoriach (a jedyne jakie mamy są dla kategorii "Programowanie") nie ma ustawionej pustej jako domyślna - żeby to zmienić wystarczy przestawić tę flagę w bazie na 1.

> Gdy ktoś nie zauważy pola, to na walidacji przy próbie dodania pytania powinien dostać błąd

Niestety walidacja tego nie sprawdza. Ponadto, walidacja w trakcie tworzenia pytania jest po stronie backendu, nie frontu - więc ewentualne błędy są pokazywane dopiero po odświeżeniu strony. Należało by więc uzupełnić walidację backendową (plik `forum\qa-include\pages\ask.php`) o sprawdzanie, czy dla kategorii "Programowanie" została wybrana jakaś podkategoria.
