### ISSUE TITLE
Brak przeładowania strony z poziomu panela powiadomień

### ISSUE THREAD

**Issue by PawelNackiewicz** [CodersCommunity/forum.pasja-informatyki.local#214]
W momencie gdy jestem w konkretnym temacie i dostanę powiadomienie o nowym wpisie do tego tematu, nie jestem w stanie przeładować strony.

Kroki do powtórzenia.

1. Wejdź w jakiś temat i zacznij w nim brać aktywny udział (dodaj komentarz, odpowiedź)
2. Wygeneruj jakieś powiadomienie do tego tematu (nie opuszczaj w tym czasie strony tematu)
3. Wejdź w powiadomienia i spróbuj kliknąć na wątek z powiadomienia.

Aktualnie zachowanie: nic się nie dzieje

Oczekiwany rezultat: strona powinna się przeładować a nowe wpisy powinny być widoczne

**Comment by ScriptyChris** [comment]
Problem naprawiony w PR #224.
