### ISSUE TITLE
Wyświetlanie linków na profilu a spamowe konta

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#226]
Do jak najszybszego rozwiązania problem, który ciągnie się od dawna, a można go prosto ukrócić.

Na swoim profilu każdy może zamieścić kilka informacji, w tym link do strony www. Oprócz tego na profilu jest ściana, gdzie może dodać jakieś wpisy on sam lub ktoś inny i tam też mogą znaleźć się linki. Problem jest taki, że wykorzystywane jest to prawdopodobnie do promowania stron (podbijania swojej pozycji w Google?). Ktoś zakłada konto, kilka kont albo bot robi to masowo, umieszcza różne linki i konto wisi puste tylko po to, aby reklamowało śmieciowy link. Głównie używane jest pole link w profilu, ale przy okazji można też zwalczyć opcję wstawienia na ścianie i upewnić się, że link nie zadziała w żadnym innym miejscu profilu.

Możemy sobie z tym poradzić na kilka sposobów:
1. Zmienić, aby link na profilu był widoczny tylko dla zalogowanych - to mogę zrobić od ręki z poziomu panelu. Google wtedy nie zobaczy tych linków, inni zalogowani nadal będą mogli. Dotknie to jednak wszystkich użytkowników, również tych którzy mają "normalne konta" i link do swojej strony oraz nie będzie miało to wpływu na ścianę. Nie wiem na ile to może być istotny problem.
2. Zrobić, aby link na profilu mógł zostać dodany przez użytkownika dopiero gdy będzie miał jakąś aktywność - najprościej chyba będzie liczyć to po punktach, np. gdy ma więcej niż 100 czy jeszcze więcej.
3. Link na profilu można dodać w każdej chwili, na ścianie użytkownik może pisać w każdej chwili, ale inni zobaczą to dopiero, gdy ten użytkownik będzie aktywny - czyli np. miał te ponad 100 czy trochę więcej punktów. Albo zarówno inni zalogowani i niezalogowani (w tym Google) mogą nie widzieć albo zalogowani mogą widzieć zawsze. W ramach niespodzianki do tej funkcji można spamerom nie mówić tego, że ich linki nie będą widoczne, oni podglądając swój profil będąc zalogowanymi mogą je zobaczyć :)

Jeśli chodzi o wspomniany limit punktowy to nie przesadzałbym z nim, obecnie takie konta w znacznej większości nie mają kompletnie żadnej aktywności. Inną opcją do ukrycia jest wyświetlenie linków tak, aby nie były klikalne. W przypadku pola profilu myślę że nie ma problemu jego ukrycie, gorzej ze ścianą, bo wtedy trzeba by wyłączyć ją całą albo właśnie np. uniemożliwić klikanie linków.

Opcja 1 jest najłatwiejsza. Osobiście najbliżej mi do opcji 3 z jakimś dopasowaniem, wydaje się że nie powinno to być trudne, a całkiem skuteczne. Kwestia ustalenia co i jak chcemy zrobić.

**Comment by event15** [comment]
Nie rozumiem czemu to jest problem, że ktoś podbija sobie w ten sposób ranking google. Jeśli to jest jedyna konsekwencja, to imho gra nie jest warta świeczki.

**Comment by awaluk** [comment]
Prawdopodobnie jedyna. IMO warta, bo takich spamowych kont jest pełno, a rozwiązanie stosunkowo proste. Nie wiem jakie konsekwencje to ma dla Googla i SEO, ale nie widzę potrzeby, aby ktoś generował pełno spamowych backlinków do siebie.
