### ISSUE TITLE
Problem z tagiem "C++"

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#254]
Sugestia od jednego z użytkowników: podczas wpisywania tagów często mylony jest "C++" z "C", ponieważ po wpisaniu tagu "C++" automatycznie usuwane są znaki ++ i wychodzi C. Można by więc "C++" w tagach automatycznie zamieniać na "c-plus-plus".

Można też od razu pomyśleć czy są inne podobne sytuacje, gdzie jakieś znaki/tagi mogą być źle używane, na razie tylko to mi przychodzi do głowy.

**Comment by ScriptyChris** [comment]
Błąd błędem, ale czy to jest faktycznie problematyczne? I tak tematy dotyczące "C" i "C++" są w tej samej kategorii. Chyba, że tagi są przydatne w wyszukiwaniu czy SEO.

**Comment by awaluk** [comment]
Są w tej samej kategorii, w bloczku na kod też jest wspólna pozycja dla C i C++, a tagi się psują - czyli finalnie jeśli autor tego jeszcze dodatkowo nie zaznaczy, to nie wiadomo, którego języka dotyczy pytanie. To jest właśnie problem.
