### ISSUE TITLE
Opcja zamiany komentarza na odpowiedź

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#263]
Czasem zdarza się, że w komentarzach do pytania rozpocznie się jakaś dyskusja i finalnie to tam padnie odpowiedź, która rozwiązuje problem. W takiej sytuacji komentarza nie można w żaden sposób oznaczyć jako rozwiązanie - tzn. pytanie nadal widnieje jako bez żadnej odpowiedzi i bez wybranej najlepszej odpowiedzi.

Aby temu zaradzić należałoby dać opcję zamiany komentarza na odpowiedź, podobnie jak działa zamiana odpowiedzi na komentarz. Mogłoby to być też jako taki checkbox na edycji komentarza. Nie można przy tym zapomnieć, że pod danym komentarzem trwa dalsza dyskusja, która może dotyczyć tego komentarza, ale nie musi, więc to też trzeba by jakoś przenosić. Idealnie byłoby dać wybór które komentarze pod komentarzem (od tego komentarza w dół) zmienianym na odpowiedź mają zostać przeniesione - i wtedy komentarz przenoszony ląduje jako odpowiedź, a wybrane komentarze jako komentarze do tej nowej odpowiedzi. To pewnie będzie trudniejsze, dlatego można to na razie pominąć i dać chociaż dodatkowy checkbox typu "przenieś komentarze pod wybranym jako komentarze do nowej odpowiedzi", który przenosiłby albo wszystko albo nic.

Należy też pamiętać o kwestii powiadomień i głosów, które zostały poruszone w #200 i #245.

**Comment by event15** [comment]
A nie lepiej byłoby dodać opcję oznaczenia komentarza jako rozwiązującego problem, co by po prostu utworzyło box odpowiedzi z jakimś reflinkiem do tego komentarza? 

1. "Oznacz komentarz jako rozwiązujący problem"
2. Komentarz dostaje zieloną ramkę
3. Ten konkretny komentarz wystawiany jest w box który wygląda jak odpowiedź (ale bez innych komentarzy, tylko z linkiem przenoszącym do właściwej dyskusji).

**Comment by awaluk** [comment]
Też miałoby to sens, ale wg mnie niepotrzebnie komplikuje całość. Bo wtedy wprowadzamy jakiś kolejny element - "box który wygląda jak odpowiedź". Co wtedy, trzeba go liczyć jako normalną odpowiedź? I na np. liście pytań będzie że ma 0 odpowiedzi i wybraną najlepszą odpowiedź? Czy że to jedna odpowiedź, a potem wchodzisz i to wcale nie odpowiedź? Jeśli to potraktujemy jako wirtualną odpowiedź to trzeba zmienić cały mechanizm wyświetlania wszystkiego, aby obsługiwał takie "inne typy" odpowiedzi, tzn. odpowiednio się zachowywał bo np. nie będzie można bezpośrednio tego edytować, ukrywać, bo to w końcu tylko taki wirtualny odnośnik. Jeśli to nie odpowiedź to trzeba z kolei zmieniać cały mechanizm wyboru najlepszej odpowiedzi, no bo już na listach trzeba uwzględnić że to może być komentarz itd.

Więc nie wiem, też można, ale to brzmi trochę jak komplikacja i obchodzenie podstawowego założenia - czyli że to odpowiedź ma odpowiadać na zadane pytanie, a komentarze są tylko do dodatkowej dyskusji.
