### ISSUE TITLE
Zbędne pogrubienie wypowiedzi za wspominką w komentarzu

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#269]
W #110 zostało dodane kiedyś automatyczne wstawianie nicka osoby na której komentarz się odpowiada, jeśli za danym komentarzem są inne. Nick ten jest wstawiany pogrubiony. Z początku działało to tak, że nick był pogrubiony, a jak się zaczynało pisać treść za nim to była już normalnym tekstem. Od pewnego czasu coś się popsuło i cała dalsza wypowiedź za nickiem pisana jest pogrubieniem. Nie wiem czy czasem na końcu nie była wstawiana jeszcze spacja, teraz jakby jej nie było, może to przez to. Niby nic wielkiego, ale powoduje to tyle, że niektórzy tego pogrubienia nie poprawiają i później cała wypowiedź jest niepotrzebnie pogrubiona.

Jeśli się da to proponuję poprawić tak, aby pisało się dalej bez pogrubienia. Jeśli to problem to może po prostu wyłączmy pogrubienie.

**Comment by awaluk** [comment]
Z tego co sprawdziłem - opisany problem występuje na Chrome 91, na Firefoxie 89 z kolei pisanie rozpoczyna się od nowej linii (tak też chyba nie było?) i bez pogrubienia.

**Comment by wizarddos** [comment]
Z tego co też zauważyłem i sprawdziłem pogrubienie uruchamia się po naciśnięciu na pole albo po usunięciu przecinka. Bez tych działań pisze się tak jak to zostało opisane czyli od nowej linii

**Comment by awaluk** [comment]
O Firefoxie mowa? Na Chrome za każdym razem jest pogrubienie, tj. tylko klikam "skomentuj", otwiera mi się pole na pisanie komentarz w którym zaczynam pisać i od razu tekst jest pogrubiony.

**Comment by wizarddos** [comment]
Tak, o Firefoxie mówię. Poza tym po kilku testach wydaje mi się że może być coś jeszcze na rzeczy z ckeditorem ale na razie nie wiem co

**Comment by ScriptyChris** [comment]
Na moje oko winna jest ta metoda [moveToPosition](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_range.html#method-moveToPosition) używana w [tym miejscu](https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/110/files#diff-ebb3c8887d430183438925b441606c0ef029b10ee379834133eccf7e93f6d032R906).

CKEditor po otwarciu okienka edytora wstawia `<p>` i w nim normalnie pisze się treść posta. Natomiast ficzer adnotacji wstawia w to `<p>` (z dodatkowym `<br>`) element `<strong>`, w którym wpisuje adnotację. Tworzy się więc:

```html
<p>
  <strong>@adnotacjaUsera,</strong>
  <br>
</p>
```

Do wspomnianej metody `moveToPosition` jako pierwszy parametr przekazywany jest element `<p>` i jako drugi parametr (pozycję umieszczenia kursora) podany jest początek końca tegoż `</p>`, ale mimo to kursor wstawiany jest przed `</strong>` - co, moim zdaniem, w ogóle nie ma sensu (z punktu widzenia CKEditora), bo to nie `<strong>` jest kontekstem dla tej metody, tylko `<p>`. Próbowałem zamienić `CKEDITOR.POSITION_BEFORE_END` na `CKEDITOR.POSITION_AFTER_END`, ale to nie pomaga.

Po pierwszej próbie debugowania nie znalazłem przyczyny problemu. Spróbuję debugować sam CKEditor, choć to nie jest łatwe, bo jego kod jest zminifikowany - trzeba się wspomagać ich [pełnym kodem źródłowym na GitHub](https://github.com/ckeditor/ckeditor4/blob/cae20318d46745cc46c811da4e7d68b38ca32449/core/dom/range.js#L1918-L1926).
