### ISSUE TITLE
Problem ze zwijaniem się bloczka kodu po kliknięciu w pasek scrolla

### ISSUE THREAD

**Issue by awaluk** [CodersCommunity/forum.pasja-informatyki.local#318]
Chodzi o funkcjonalność z #301. Oryginalne zgłoszenie: https://forum.pasja-informatyki.pl/580447/podglad-bloczka-kodu-nie-da-sie-kliknac-paska-przewijania

Okazuje się, że występuje problem zwężania się bloczka do początkowego rozmiaru po kliknięciu na pasek scrolla. Blok wraca wtedy do pierwotnego rozmiaru, a powinien nadal pozostać rozszerzony co najmniej do momentu zwolnienia kliknięcia (lub dłużej gdy kursor pozostaje nadal na bloku). Gdy sprawdzałem u siebie na Chrome czy Firefoxie to tego problemu nie ma, ze zgłoszenia wynika, że występuje na Chromium. Pod linkiem są również filmiki pokazujące sytuację.

**Comment by overcq** [comment]
W Chromium 132.0.6834.46 problem już nie występuje, co może być związane z naprawieniem [tego błędu](https://issues.chromium.org/issues/41314367). Wydaje się, że to był błąd przeglądarki ‘www’ w połączeniu z niektórymi menedżerami okien (np. Fluxbox).

**Comment by awaluk** [comment]
Faktycznie, wydaje się, że teraz już działa. Dzięki za weryfikację i info.
