### ISSUE TITLE
Przygotowanie backendu pod żądanie POST - obsługa dla "powód zgłoszenia" postu

### ISSUE THREAD

**Issue by JSHoliq** [CodersCommunity/forum.pasja-informatyki.local#32]
Czy mógłby ktoś przygotować bazę danych oraz serwer PHP, aby przyjął POSTa z parametrem, którym będzie powód zgłoszenia dla postu/tematu?

Chodzi mi o tą propozycję: https://trello.com/c/OKykXnFA/19-zg-oszenie-powinno-miec-powod
Mogę zrobić skrypt, który wyświetli pole do opisania powodu zgłoszenia i wyśle ten powód na serwer, aby sobie Moderatorzy mogli go odczytać. Tylko wydaje mi się że najpierw trzeba to obsłużyć po stronie serwera.

**Comment by event15** [comment]
Najpewniej będę chciał się za to wziąć - sprawdzę u siebie w którym miejscu jest wywoływany kod ze zgłaszaniem i pomyślę jak zrobić zapis i odczyt tego z bazki danych.

**Comment by efiku** [comment]
@event15,  w sumie można pomyśleć o rozpoczęciu separowania większych zmian.  Dodanie niezależnego routingu pod /api/[xxx]
Wpiąć się do miejsca gdzie przetwarzany jest routing i wahooooo

**Comment by awaluk** [comment]
Już poruszone ogólniej m.in. w #69 
Prace w trakcie #138 #143 #160 #163
