### ISSUE TITLE
Błędne kolorowanie komentarzy blokowych (Java)

### ISSUE THREAD

**Issue by sheadovas** [CodersCommunity/forum.pasja-informatyki.local#50]
Przy kolorowaniu składni - konkretnie komentarzy blokowych - nie jest wychwytywane zakończenie komentarza i reszta kodu jest kolorowana jak komentarz. Ten sam kod, ale z wybranym CPP jest kolorowany poprawnie.

Problem został znaleziony w ramach pisania komentarza do odpowiedzi
```java
public int Newton(int n=3,int k=2)
   {
      if(k /* 2 */ == 0 || k /* 2 */ == n /* 3 */)
          return 1;
      else
          return Newton(--n /* --3 -> n=2 */,--k /* --2 -> k=1 */) 
               + Newton(--n /* --2 -> 1 */ ,k /* 1 */);
   }
```
![capture](https://cloud.githubusercontent.com/assets/5824063/19212557/d6d609f8-8d53-11e6-94df-43eac281f120.PNG)

**Comment by ChrissP92** [comment]
To może być jakiś bug w CKEditorze lub w pluginie **syntaxhighlighter**. Ficzery mojego autorstwa, które "upiększają" bloczki, nie ingerują w ich kolorowanie ani rozpoznawanie kodu.

**Comment by sheadovas** [comment]
Mi to śmierdzi **syntaxhiglighterem**

**Comment by efiku** [comment]
Naprawione zostało w #51 
Jeżeli #51 zostanie zmergowane to  Zamknąć ;)

![img](http://image.prntscr.com/image/7bdbb857d6354092b69adfda64734e7d.png)
