### ISSUE TITLE
[Idea] Wyłączenie menu kontekstowego edytora

### ISSUE THREAD

**Issue by sheadovas** [CodersCommunity/forum.pasja-informatyki.local#65]
Obecnie edytor tekstowy na forum jest dość ubogi i nie radzi sobie nawet z np. poprawianiem literówek znalezionych przez przeglądarkę.

![ctxmenu](https://cloud.githubusercontent.com/assets/5824063/20305775/75261aac-ab37-11e6-9dd2-8403995e00a5.PNG)

Pomysł jest taki aby wyłączyć nakładkę odpowiadającą za zastąpienie menu kontekstowego i pozostawienie tego używanego przez przeglądarkę

**Comment by awaluk** [comment]
Przyciśnij CTRL i wtedy kliknij prawym.

Ja jetem za, to menu od CKEditora nie za wiele daje i myślę, że spokojnie mogłoby wyświetlać się właściwe menu kontekstowe przeglądarki. A o powyższej możliwości wyświetlenia tegoż menu pewnie mało kto wie (prawie nikt?) i wciskanie co chwilę CTRL nie wydaje się zbyt wygodne.

**Comment by xandros15** [comment]
Nie ma jakiś parserów markdown? Takie jak są na gitcie lub BB

**Comment by sheadovas** [comment]
UP Jacyś chętni do wyłączenia tego featera?

**Comment by awaluk** [comment]
Zrobione.
