### ISSUE TITLE
[Idea] Zmiana edytora tekstu

### ISSUE THREAD

**Issue by sheadovas** [CodersCommunity/forum.pasja-informatyki.local#66]
Obecny edytor tekstu / kodu na forum jest dość ubogi w funkcje (szczególnie jeżeli chodzi o formatowanie tekstu bez ręcznego zaznaczania tekstu i klikania myszą w ikonki), myślę że można by się pokusić o inny edytor, np oparty o [Markdown](https://daringfireball.net/projects/markdown/)

Istnieje nawet [plugin](https://github.com/svivian/q2a-markdown-editor) pod Q2A, ale podejrzewam, że trzeba by go nieco poprawić.

**Comment by awaluk** [comment]
Pierwsze co trzeba by zrobić to zastanowić się jak przenieść wszystkie posty, które aktualnie są w bazie na markdown (bo wyobrażam sobie, że plugin ten trzyma posty w bazie jako markdown i przy wyświetlaniu zamienia na HTML). Gdyby były z tym jakiekolwiek problemy to nawet nie ma co zaczynać myśleć o zmianie edytora.

A co do samej zmiany to jestem hm, neutralny. Markdown jest spoko i mógłby być, ale z CKEditorem też nie jest wg mnie tak źle i skoro już jest to nie wiem czy jest sens się bawić w tak dużą zmianę.

**Comment by sheadovas** [comment]
Jeżeli zostanie wprowadzony #65 to to też mi się wydaje że warto pozostać przy obecnym edytorze, chociaż nie obraziłbym się za dorzucenie jakichś skrótów klawiszowych / możliwości edytowania kodu używając tylko klawiatury ;)

**Comment by efiku** [comment]
A jakich funkcji niby jeszcze potrzebujesz w tym edytorze?

Wyłączenie autoformatowania to po prostu kompromis pomiędzy kopiowaniem
zaznaczonego tekstu i wklejaniem go do edytora. Paskudnie to wyglądało i
osobiście więcej czasu spędziłem na zamianie tego na normalny tekst.
