### ISSUE TITLE
Zgłoszenie posta/odpowiedzi

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/forum.pasja-informatyki.local#69]
W celu poprawy w zgłaszaniu śmieciowych pytań i odpowiedzi sugeruję przepisać skrypt JS który odpowiada za zgłaszanie.

**Problem:**
Gdy kliknę zgłoś temat/odpowiedź następuje denerwujące odświeżenie strony, które powoduje, że zasysane zostają dodatkowe grafiki itd.

**Rozwiązanie:**
Sugeruję przepisać funkcję zgłaszania tak, aby nie trzeba było do tego odświeżać stronę.  (Po wykonaniu requesta, zmieniać ikonkę i dodawać ten czerwony napis)

**Comment by sheadovas** [comment]
Przy okazji można by było dodać powód zgłoszenia, poprzez wybór z listy rozsuwającej się po kliknięciu na ikonkę flagi. Przykładowe powody zgłoszenia:
- **Duplikat** duplikat innego pytania
- **Zła kategoria** temat trafił do złej kategorii
- **Spam** temat niepasujący do tematyki forum, np reklama wygenerowana przez bota, 
- **Inny powód** inny powód, który powoduje łamanie regulaminu

Dobrym powodem byłoby też dorzucić do wygenerowanego raportu informacji o użytkowniku który zgłasza, tzn w widoku zgłoszonych nicków widać byłoby od teraz listę z powodami zgłoszenia oraz osób które stworzyły dane zgłoszenie.

**Comment by awaluk** [comment]
Popieram pomysł poprawy opisany przez @efiku, co do powodu proponowanego przez @sheadovas też się zgadzam (z resztą zamiar wprowadzenia powodu jest już od dawna - patrz #32 lub [tu](https://trello.com/c/OKykXnFA/19-zg-oszenie-powinno-miec-powod)). Oprócz tych przykładowych powodów chyba jednak wrzuciłbym też pole tekstowe, aby można było wpisać zupełnie własny powód - gdy jest to zła kategoria lub duplikat to przeważnie osoba oceniająca zgłoszenie to widzi, problem i zastanowienie pojawia się gdy jest zgłoszenie, a w poście nie widać nie złego. Oczywiście to do oceniającego zgłoszenie należy decyzja i jeśli nie ma w tym nic złego to zostanie wycofane, ale sądzę że jeśli już wprowadzamy ten powód, który ma to ułatwić to powinna być też możliwość podania całkowicie własnego powodu, który naprowadzi administracje na występujący tam problem.

Osoba zgłaszająca powinna być widoczna dla całej administracji, w chwili obecnej widzę to tylko ja jako administrator. Podobnie oczywiście powód.

**Comment by sheadovas** [comment]
Jasne, pole tekstowe jest bardziej sensowne, mniej zabawy z listami i bardziej konkretny opis

**Comment by awaluk** [comment]
Praca nad powodami zgłoszeń trwa, temat poruszany w wielu miejscach #138 #143 #160 #163

**Comment by ScriptyChris** [comment]
Temat ogarnięty w #199.
