### ISSUE TITLE
Pytania bez odpowiedzi

### ISSUE THREAD

**Issue by korneliakobiela** [CodersCommunity/forum.pasja-informatyki.local#7]
Nie wiem, może coś takiego jest ale jeszcze nie znalazłam. Na innych forach o podobnej budowie działa coś takiego jak pytania bez odpowiedzi. Wiem, że póki co jest ich stosunkowo mało, ale może dałoby się zaimplementować taką właściwość. Po prostu ja czasem wchodzę na forum i chciałabym szybko komuś pomóc, zobaczyć, czy ktoś nie potrzebuje odpowiedzi. Nie każdy uzyskuje ją od razu. Pozdrawiam

**Comment by efiku** [comment]
http://forum.pasja-informatyki.pl/unanswered , to? :)

**Comment by awaluk** [comment]
Jest taka funkcjonalność u nas, tyle że nie ma do niej widocznego przycisku. Chociaż właśnie w [pytaniu o zmiany w menu](http://forum.pasja-informatyki.pl/153637/przebudowa-menu-i-stopki-forum) zapytałem, czy warto byłoby go dodać. Nawet bez przycisku jest do tego dostęp: http://forum.pasja-informatyki.pl/unanswered

**Comment by korneliakobiela** [comment]
Ok, na forum jestem ok 2 miesiące, fajnie że jest zaimplementowane, tylko szkoda, że tego nie widać. Jestem jak najbardziej za wrzuceniem do menu. Dzięki za pomoc i przepraszam za kłopot :)

**Comment by awaluk** [comment]
Żaden kłopot, nie ma problemu ;)
