### ISSUE TITLE
qa-body-wrapper nachodzi na nawigacje

### ISSUE THREAD

**Issue by xandros15** [CodersCommunity/forum.pasja-informatyki.local#8]
Sprawdzone na chrome: Version 51.0.2704.103 m

Jak wygląda: https://i.imgur.com/H0eZ1Vk.png

Jak powinno wyglądać: https://imgur.com/6IYM9Qb

Jak naprawić: Usunąć z `.qa-body-wrapper` `margin: -3px auto !important;`, który jest wpisany inline

**Comment by efiku** [comment]
To zostało już naprawione??

**Comment by event15** [comment]
https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/9

**Comment by efiku** [comment]
No to zamykajcie issue, albo chociaż ref do nich w PR.
