### ISSUE TITLE
Uwaga!

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/forum.pasja-informatyki.local#88]
Moi drodzy, trzeba coś zrobić z tymi polecanymi książkami od Heliona.
Spróbuję do nich napisać, aby poprawili to, zwracając chociażby jsona...

### Problem?
Często pada im to, co uniemożliwia poprawne załadowanie strony, chociażby naszego ckeditora. 

### Rozwiązanie?

- Wyrzucić to coś
- Napisać do nich maila.

**Comment by event15** [comment]
A nie można ich ładować dopiero po załadowaniu strony? document ready w js jakieś :)

**Comment by efiku** [comment]
Tam jest document.write

Krzysztof Pazdur

30.01.2017 20:04 "Marek Woś" <notifications@github.com> napisał(a):

**Comment by Argeento** [comment]
Może nie najpiękniejsze, ale jakieś rozwiązanie by się może znalazło

Wrzucić na sam koniec strony -> złapać CSS-em (display: none)
Ustawić listener na skrypt -> onload sprawdzić czy helionowi udało się coś napisać -> jeśli tak, przepisać HTMLa we właściwe miejsce.

**Comment by efiku** [comment]
Niebawem będę do nich pisać maila w tej sprawie.
Zazwyczaj skrypt nie działa gdy oni zepsują coś na produkcji.  Skrypt u nas
czeka i czeka az dostanie odpowiedź,  po chwili dostaje 504. :)
Może przeniesienie skryptu na koniec body coś pomoże ?

Ping @Comandeer

Krzysztof Pazdur

01.02.2017 01:05 "Adrian Wieprzkowicz" <notifications@github.com>
napisał(a):

**Comment by event15** [comment]
Zrobić to w iframe i mieć z głowy :) Ustawić w js by nie ładował się div dopóki forum się nie załaduje i na samym końcu ładowac helionowe rzeczy. Wątpię być cokolwiek osiągnął pisząc do nich.

**Comment by Comandeer** [comment]
Można podmienić `document.write`, żeby podmieniał aktualny skrypt na generowaną zawartość. [Robiłem to już kiedyś](https://gist.github.com/Comandeer/abf67165097d51b63875).

**Comment by awaluk** [comment]
Akurat pani z Helionu ostatnio sama do mnie napisała z zachętą do współpracy, więc w odpowiedzi odpisałem co sądzę o ich programie partnerskim w kwestiach tylko technicznych. Zacytuję ze swojej wiadomości:

>- Państwa serwery sporadycznie co jakiś czas są chwilowo niedostępne. Wiąże się to z tym, że wtedy też strona naszego forum przestaje poprawnie działać. Prawdopodobnie przeglądarka czeka na załadowanie skryptu od programu z waszych serwerów i do tego czasu blokuje wykonanie reszty kodu, przez co część naszego forum nie jest widoczna, strona jakby ciągle się ładowała, ale nie mogła.
>- Próbowałem samemu dodać do skryptu atrybut async, aby skrypt był pobierany asynchronicznie (bez czekania na jego załadowanie) jednak jest to niemożliwe, gdyż w skrypcie użyte jest document.write.
>- Również niemożliwe jest przesunięcie wczytywania skryptu na sam koniec sekcji body (a tak powinno być zrobione), gdyż wyświetlany jest przez wspomniany document.write, czyli w miejscu wykonania.
>- Wszystkie zasoby (w tym pliki okładek książek wyświetlane na stronie) pobierane są automatycznie przez protokół http - w skrypcie jest to na stałe wpisane i nijak nie można tego zmienić. W razie przejścia forum na https wszystkie zasoby ładowane na stronie powinny być pobierane przez https, aby przeglądarka uznała stronę za bezpieczną. W związku z tym również wasz program partnerski powinien pobierać dane przez https, które staje się już standardem na wielu stronach.

W odpowiedzi uzyskałem informację, że pani "omówi uwagi z działem IT". Dzisiaj po raz kolejny trafiłem moment gdy serwery Helionu nie działały, przez co forum ładowało się do pewnego momentu i od razu ponownie do pani napisałem. Tym razem pokazałem żywy dowód (strona właśnie w tym momencie nie działała) oraz poinformowałem, że trwale usuwam program partnerski i dopóki nie zostanie poprawiony nie może działać na naszym forum gdyż jest wyjątkowo uciążliwy. W odpowiedzi otrzymałem informację, że "przekazała prośbę i postarają się wypracować jakieś rozwiązanie".

Czy coś z tego będzie czy nie, to ciężko powiedzieć. Na tę chwilę problem jednak jest zażegnany, "Okazji od Heliona" na stronach forum nie ma i nie planuję jej przywrócić dopóki nie zajdzie zmiana na lepsze.

**Comment by efiku** [comment]
Jak ich dział IT nauczy się co to JSON i jak tego używać  to może wtedy ;D

**Comment by awaluk** [comment]
Po kilku wymienionych mailach, dziwnych propozycjach obejścia i długiej ciszy dostałem wreszcie zapewnienie, że dane książki-okazji będzie można również pobrać w formacie JSON, o który prosiłem.
Tak więc zmierza to w dobrą stronę, ale z ogłoszeniem sukcesu jeszcze poczekajmy aż faktycznie się pojawi :)

**Comment by efiku** [comment]
Muszą personel przeszkolić. :)
To czekamy

W dniu 27 lutego 2017 12:15 użytkownik Arkadiusz Waluk <
notifications@github.com> napisał:

**Comment by efiku** [comment]
Update.
Mamy już API. 
@awaluk  napisał wersję w PHP ale ja jestem przeciwnikiem tego rozwiązania, wolę aby to przenieść na przeglądarkę usera. 

```js
(function() {

})()

```
:)

**Comment by awaluk** [comment]
Moim pomysłem było jak największe uniezależnienie się od serwerów Heliona, stąd przygotowałem sobie prostą biblioteczkę w PHP, która codziennie po północy miałaby pobrać dane i cachować u nas na serwerze, w pliku, i tylko wyświetlać przy ładowaniu strony. Myślałem nawet o pobieraniu samego obrazu okładki do nas (obecnie jest/był brany z serwerów Helionu), aby nie było problemów i z dostępem do tego, ale na razie odpuściłem.
W każdym razie to że ja sobie coś napisałem, to nie znaczy że musi od razu wchodzić na forum, więc możemy śmiało myśleć nad innym rozwiązaniem :)

Gdyby ktoś chciał zobaczyć moje rozwiązanie: https://github.com/awaluk/helion-special-offer
A tutaj link do JSONa od Helionu: https://helion.pl/plugins/new/promocja.phi?nr=xx&size=181&type=json
