### ISSUE TITLE
Język używany w issues i w projekcie

### ISSUE THREAD

**Issue by event15** [CodersCommunity/forum.pasja-informatyki.local#95]
Na przyszłość ustandaryzujmy się trochę. 
Wchodzi się tu i raz się widzi issues po angielsku raz po polsku. Tak samo z komentarzami. README.md jest całkowicie po polsku, jesteśmy polakami więc już komentujmy po polsku bo to wprowadza niepotrzebny chaos.

**Comment by efiku** [comment]
I nie commitujmy przez GH! *_* Zgadzam się

**Comment by efiku** [comment]
Swoją drogą... Każde PR mergowane powinno być ze squashem...
