### ISSUE TITLE
Niedziałający 403 Forbidden dla '/images'?

### ISSUE THREAD

**Issue by klusaktomasz** [CodersCommunity/forum.pasja-informatyki.local#96]
Gdy wchodzimy pod [forum.pasja-informatyki.pl/images][fpi/images] dostajemy 403 Forbidden z zawartością strony głównej, która ze względu na link nie może dostać się do CSS-a i JS-a.

Nawet jakby ktoś chciał skorzystać z "trzeciego motywu", bez CSS-a to nie ma takiej możliwości, ponieważ linki nie działają (przed każdym jest /images).

Dodatkowo, jedynym motywem jaki można wybrać to Ciemny, nawet gdy z niego korzystamy, więc może jest jeszcze jakieś miejsce, w którym motywy nie działają/zachowują się dziwnie :)

[fpi/images]: https://forum.pasja-informatyki.pl/images

**Comment by awaluk** [comment]
Zgadza się, jest jakiś błąd powodujący sypanie się strony błędów. Dopisałem też na Trello żeby nie przeoczyć.

>Dodatkowo, jedynym motywem jaki można wybrać to Ciemny, nawet gdy z niego korzystamy, więc może jest jeszcze jakieś miejsce, w którym motywy nie działają/zachowują się dziwnie :)

Nie za bardzo rozumiem? Założenie jest takie, że można wybrać albo jasny (domyślny) motyw, albo nowy ciemny. W każdej chwili można się między nimi przełączać. Innych motywów na razie nie ma i nie są na tę chwilę planowane.

**Comment by klusaktomasz** [comment]
Prościej: Na stronie błędu zawsze jest wybrany Jasny motyw (przycisk do wybrania motywów jest tylko dostępny dla Ciemnego, czyli jest wybrany Jasny).

Wspomniałem o tym, ponieważ dziwi mnie fakt, że motywy miały się zapisywać na serwerze, więc dlaczego w tym przypadku nie zadziałały? No chyba, że zmianą dostępnego przycisku zajmuje się JS. Wtedy wszystko OK, ale jeżeli jednak tak nie jest to możliwe jest, że motywy też się wysypią w jakiś innych, "dziwnych" miejscach.

**Comment by awaluk** [comment]
Ach, teraz rozumiem, w porządku. Motyw jest zapisywany przez PHP na serwerze, więc nie powinien się sypać. Zbadamy to.

**Comment by awaluk** [comment]
Samo wyświetlanie strony naprawione dawno temu w #130, ale nadal jest problem z wyborem motywu z poziomu strony błędu

**Comment by awaluk** [comment]
Wejście na sam adres jakiegoś katalogu rzuca teraz 403 z samego serwera i nie pokazuje w ogóle strony forum, a więc problem w pewnym sensie jest rozwiązany.
